### ISSUE TITLE
Looks like a good app

### ISSUE THREAD

**Issue by lovebdsobuj** [AfaanBilal/Live-HTML-Editor#1]
It's would be very good if you add an option for **`hide/show`** preview tab from menu or shortcuts key `ctrl+p`

**Comment by AfaanBilal** [comment]
Thanks for the request. It has been quite some time since I have worked on this app, and I'm quite busy so I may not get around to doing this but perhaps I will. In the meantime, you are welcome to do it and open a pull request.

**Comment by lovebdsobuj** [comment]
The type or namespace name '`FastColoredTextBoxNS`' could not be found!
Got 16 error in `MainForm.cs` file.

**Comment by AfaanBilal** [comment]
Have you added FastColoredTextbox as a reference to you project? Check your references and DLL paths.

**Comment by lovebdsobuj** [comment]
Sorry, forgot to add `FastColoredTextBox.dll` as Reference.

**Comment by lovebdsobuj** [comment]
Can you give me short hints to do that?

**Comment by AfaanBilal** [comment]
http://stackoverflow.com/questions/12992286/how-to-add-a-dll-reference-to-a-project-in-visual-studio

**Comment by lovebdsobuj** [comment]
I added the dll file & it's works very well.
I need little hints for show/hide preview tab from menu or shortcuts key ctrl+p.

**Comment by AfaanBilal** [comment]
Add a menu (preferably a checkbox) which calls `wbMain.Visible = !wbMain.Visible;` to toggle visibility of the preview tab.

**Comment by lovebdsobuj** [comment]
Thank you so much, It's working!
![live html editor](https://cloud.githubusercontent.com/assets/10352682/21145864/f941d47c-c179-11e6-8b59-520f649c7214.gif)

**Comment by AfaanBilal** [comment]
You're welcome! Push the code and open a pull request and I'll merge it.
